import React from "react";
import "./App.css";
import { Switch, Route, Redirect } from "react-router-dom";
import HomePage from "./pages/homepage/homepage.component";
import ShopPage from "./pages/shop/shop.component";
import CheckoutPage from "./pages/checkout/checkout.component.jsx";
import Header from "./components/header/header.component";
import {
  auth,
  createUserProfileDocument
  // **TEMP** - addCollectionAndDocuments for adding shop data to fb
  /*, addCollectionAndDocuments*/
} from "./firebase/firebase.utils";
import { connect } from "react-redux";
import { setCurrentUser } from "./redux/user/user.actions";
import { selectCurrentUser } from "./redux/user/user.selectors";
// *TEMP* - selectCollectionsForPreview is for adding shop data to fb
// import { selectCollectionsForPreview } from "./redux/shop/shop.selectors";
import { createStructuredSelector } from "reselect";
import SignInAndSignUpPage from "./pages/sign-in-and-sign-up/sign-in-and-sign-up.component";

class App extends React.Component {
  unsubscribeFromAuth = null;

  componentDidMount() {
    // **TEMP** collectionsArray is for adding shop data to Firebase (remove once added)
    const { setCurrentUser /*, collectionsArray*/ } = this.props;

    // onAuthStateChanged is open subscription between app and firebase which lets us know
    // when authentication state has changed without having to fetch manually.
    // auth.onAuthStateChanged returns a function which when executed will close script subscription.
    // @param userAuth: user authenticated object from Auth library, which persists when refreshing page. Includes user ID generated by FireStore (UID)
    this.unsubscribeFromAuth = auth.onAuthStateChanged(async userAuth => {
      if (userAuth) {
        // get userReference from db or create one
        const userRef = createUserProfileDocument(userAuth);

        // onSnapshot() subscribes to userRef and listens for any changes. Returns snapShot of user object. Also returns initial state first time code is executed.
        // snapShot.data() method gives us actual properties on the snapshot object (aka data)
        (await userRef).onSnapshot(snapShot => {
          setCurrentUser({
            currentUser: {
              id: snapShot.id,
              ...snapShot.data()
            }
          });
        });
      } else {
        // If user signs out, set currentUser to null
        setCurrentUser(userAuth);
        /*
        *TEMP* Add shop data to firestore - only want title and items (firebase will generate id and routeName)
        addCollectionAndDocuments(
          "collections",
          collectionsArray.map(({ title, items }) => ({ title, items }))
        );
        */
      }
    });
  }

  componentWillUnmount() {
    // Close subscription to firebase to prevent memory leaks from open connection.
    this.unsubscribeFromAuth();
  }

  render() {
    return (
      <div>
        <Header />
        <Switch>
          <Route exact path="/" component={HomePage} />
          <Route path="/shop" component={ShopPage} />
          <Route exact path="/checkout" component={CheckoutPage} />
          {/* If user signed in, redirect user to home page when clicking signin.
            also redirects to home when user signs in.
          render prop determines what component to return*/}
          <Route
            exact
            path="/signin"
            render={() =>
              this.props.currentUser ? (
                <Redirect to="/" />
              ) : (
                <SignInAndSignUpPage />
              )
            }
          />
        </Switch>
      </div>
    );
  }
}

const mapStateToProps = createStructuredSelector({
  currentUser: selectCurrentUser
  // **TEMP** - selectCollectionsForPreview is for adding shop data to fb
  // , collectionsArray: selectCollectionsForPreview
});

const mapDispatchToProps = dispatch => ({
  // component > propName: payload => dispatch(action(payload)) > reducer > root-reducer(store)
  // setCurrentUser(user) returns the object from user action which includes action type and payload
  // that action is then dispatched to user reducer and then to root-reducer
  setCurrentUser: user => dispatch(setCurrentUser(user))
});

export default connect(mapStateToProps, mapDispatchToProps)(App);
